version: "3.8"

services:
  game_auth:
    build:
      context: ./Game_auth
    restart: always
    networks:
      - backend
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: production
      PORT: 5000
    depends_on:
      - db

  game_socket:
    build:
      context: ./GameSocket
    restart: always
    networks:
      - backend
    ports:
      - "7000:7000"
    environment:
      NODE_ENV: production
      PORT: 7000
    depends_on:
      - db

  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dbGameMarket
    restart: always
    volumes:
      - ./init-db-game.sh:/docker-entrypoint-initdb.d/init-db-game.sh
      - db-data-game:/var/lib/postgresql/data
      - ./scripts:/scripts
    ports:
      - "5432:5432"
    networks:
      - backend

  game_marketplace:
    build:
      context: ./game-marketplace
    restart: always
    ports:
      - "12000:80"
    networks:
      - frontend
    depends_on:
      - game_auth
      - game_socket

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

volumes:
  db-data-game:
