name: Full CI Workflow

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: dbGameMarket
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install and Test Game_auth
      run: |
        echo "Installing and testing Game_auth"
        cd Game_auth
        npm install
        npm test
      env:
        PGHOST: localhost
        PGDATABASE: dbGameMarket
        PGUSER: postgres
        PGPASSWORD: postgres

    - name: Install and Test GameSocket
      run: |
        echo "Installing and testing GameSocket"
        cd GameSocket
        npm install
        npm test
      env:
        PGHOST: localhost
        PGDATABASE: dbGameMarket
        PGUSER: postgres
        PGPASSWORD: postgres

    - name: Install and Test game-marketplace
      run: |
        echo "Installing and testing game-marketplace"
        cd game-marketplace
        npm install
        npm test

    - name: Cache npm dependencies
      uses: actions/cache@v2
      with:
        path: |
          Game_auth/node_modules
          GameSocket/node_modules
          game-marketplace/node_modules
        key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-npm-
