name: Full CI Workflow

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: dbGameMarket
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.18.1'
        cache: 'npm'

    - name: Install and Test Game_auth
      run: |
        cd Game_auth
        npm install
        npm test
      env:
        PGHOST: localhost
        PGDATABASE: dbGameMarket
        PGUSER: postgres
        PGPASSWORD: postgres

    - name: Install and Test GameSocket
      run: |
        cd GameSocket
        npm install
        npm test
      env:
        PGHOST: localhost
        PGDATABASE: dbGameMarket
        PGUSER: postgres
        PGPASSWORD: postgres

    - name: Install and Test game-marketplace
      run: |
        cd game-marketplace
        npm install
        npm test
